name = "Boggle Clone"
description = "A clone of the popular game, Boggle."
packages = ["numpy", "requests", "rich"]
[files]
"https://raw.githubusercontent.com/JefeThePug/Boggle/refs/heads/main/helper.py" = "./helper.py"
"https://raw.githubusercontent.com/JefeThePug/Boggle/refs/heads/main/board.py" = "./board.py"
