name = "Wordle Clone"
description = "A clone of the popular browser game, Wordle, for the terminal."
packages = []
[files]
"https://raw.githubusercontent.com/JefeThePug/Wordle/refs/heads/main/wordle_beta.py" = "./content.py"
